# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89ec9c36b03042516a509e9c3421b86cbfad54e10b7b781eea1559fc18e71942a4bf862500135ae351dff0f5c2656c727bbeaf393f66bbf7c0c6d62502f1d211

test:
  secret_key_base: ae105403ca38bedc967a10e36043c6ed24faaabb2723c3bf59075e43aa9684d74113fccfa31c1f84d57c94760b287aa1a77d1340833e017ed424f509816f7cf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
